source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BrowsePictureViewController_Example', :exclusive => true do
  pod 'BrowsePictureViewController', :path => '../'
end

target 'BrowsePictureViewController_Tests', :exclusive => true do
  pod 'BrowsePictureViewController', :path => '../'

  
end
